development:
  ADMIN_USERNAME: superadmin
  ADMIN_EMAIL: superadmin@test.com
  ADMIN_PASSWORD: "321321321"
  GMAIL_USERNAME: test@gmail.com
  GMAIL_PASSWORD: test123
  AWS_ACCESS_KEY: test123
  AWS_SECRET_KEY: dfsfsdf/8ICFtGr63/9
  AWS_BUCKET_NAME: test_development
  AUTHORIZATION: "sdfsdfsdf"
  STRIPE_PUBLISHABLE_KEY: "pk_test_oZFibScUyN5lSHeTxAyy2DbU"
  STRIPE_SECRET_KEY: "sk_test_MbXsFCHEpPEBOHyomiyYnC6y"
test:
  ADMIN_USERNAME: superadmin
  ADMIN_EMAIL: superadmin@test.com
  ADMIN_PASSWORD: "321321321"
  GMAIL_USERNAME: test@gmail.com
  GMAIL_PASSWORD: test123
  AWS_ACCESS_KEY: test123
  AWS_SECRET_KEY: dfsfsdf/8ICFtGr63/9
  AWS_BUCKET_NAME: test_development
  AUTHORIZATION: "sdfsdfsdf"
  STRIPE_PUBLISHABLE_KEY: "pk_test_oZFibScUyN5lSHeTxAyy2DbU"
  STRIPE_SECRET_KEY: "sk_test_MbXsFCHEpPEBOHyomiyYnC6y"
production:
  ADMIN_USERNAME: superadmin
  ADMIN_EMAIL: superadmin@test.com
  ADMIN_PASSWORD: "321321321"
  GMAIL_USERNAME: test@gmail.com
  GMAIL_PASSWORD: test123
  AWS_ACCESS_KEY: test123
  AWS_SECRET_KEY: dfsfsdf/8ICFtGr63/9
  AWS_BUCKET_NAME: test_development
  AUTHORIZATION: "sdfsdfsdf"
  STRIPE_PUBLISHABLE_KEY: "pk_test_oZFibScUyN5lSHeTxAyy2DbU"
  STRIPE_SECRET_KEY: "sk_test_MbXsFCHEpPEBOHyomiyYnC6y"