ADMIN_USERNAME: superadmin
ADMIN_EMAIL: superadmin@delvo.com
ADMIN_PASSWORD: "321321321"
GMAIL_USERNAME: attribesolution@gmail.com
GMAIL_PASSWORD: WaSGyu8HE84z
AWS_ACCESS_KEY: AKIAJDQMQSJLG2IVF6TQ
AWS_SECRET_KEY: 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
AWS_BUCKET_NAME: delvo_development
AUTHORIZATION: "Basic NDlhMmRiZTExN2E0NDdjZWFmYjhiOTZiNTIwMTE2ZTY6ZDYzODQ0YjU2MDE3NDI4NjlhODQwNzRhYWZmNGNiNjY="
