# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82efce2b415dcae67f21b89aacd0d65fe03800a84ec10df8b16896f3eb38008e5dd7c94777a69ace993c41ebeea9fe211d4c52af7a32129bedb68d5096f37cc1

test:
  secret_key_base: c4b7bca6fa3f8228b5bf194ff22e8a3a1c2b43de9c9b485788051a3e4c2ebcc96c9c1e121c6174bed46f612dc4031a9bf5f4e218cf745184a4b09ee8b79e3fc0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
